# Generated by Django 5.1.1 on 2024-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATLFoodFinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
